application: guestbook
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: assets/stylesheets
- url: /javascripts
  static_dir: assets/javascripts
- url: /images
  static_dir: assets/images
- url: .*
  script: guestbook.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
